apps/goods/models.py
from extends import db


class Goods(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    goods_name = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Float, nullable=False)
    # 因为用户和商品是多对多关系，无法直接添加外键，所以要依赖第三张关系表来建立relationship，secondary=第三张表表名
    # relationship里的backref的值可以随便起,用来反向引用
    users = db.relationship('User', backref='goods_list', secondary='user_goods')

    __table_args__ = {
        'extend_existing': True,
        'mysql_charset': 'utf8'
    }

    def __str__(self):
        return self.goods_name


# 创建多对多关系表----第一种方式
# tags = db.Table('tags',
#        db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
#         db.Column('page_id', db.Integer, db.ForeignKey('page.id'))
#     )


class UserGoods(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    goods_id = db.Column(db.Integer, db.ForeignKey('goods.id'))
    number = db.Column(db.Integer, default=1)

    __table_args = {
        'extend_existing': True,
        'mysql_charset': 'utf8'
    }

apps/goods/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from apps.users import models as user_model
from apps.goods import models as goods_model
from extends import db

goods_bp = Blueprint('goods', __name__)


# 根据用户找商品，查看用户买了哪些商品
@goods_bp.route('/find_goods', endpoint='find_goods')
def find_goods():
    user_id = request.args.get('user_id')
    user = user_model.User.query.get(user_id)
    return render_template('goods/find_goods.html', user=user)


# 根据商品找用户，哪些用户买了这件商品
@goods_bp.route('/find_user', endpoint='find_user')
def find_user():
    goods_id = request.args.get('goods_id')
    goods = goods_model.Goods.query.get(goods_id)
    return render_template("goods/find_user.html", goods=goods)


# 用户买商品
@goods_bp.route('/show', endpoint='show')
def show():
    if request.method == 'GET':
        users = user_model.User.query.filter(user_model.User.is_delete == False).all()
        goods_list = goods_model.Goods.query.all()
        context = {
            'users': users,
            'goods_list': goods_list
        }
        return render_template('goods/show.html', **context)
    else:
        return ''


@goods_bp.route('/buy', endpoint='buy')
def buy():
    user_id = request.args.get('user_id')
    goods_id = request.args.get('goods_id')
    user_goods = goods_model.UserGoods(user_id=user_id, goods_id=goods_id)
    print(user_id, goods_id, user_goods)
    db.session.add(user_goods)
    db.session.commit()
    u_g = goods_model.UserGoods.query.all()
    return render_template('goods/user_goods.html', u_g=u_g)

templates/goods/find_goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--  要求当前页面使用IE浏览器最高版本的内核来渲染-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0">
    <meta charset="UTF-8">
    <title>find_goods</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<h1>用户名:{{ user.username }}</h1>
<h2>此用户买的商品如下</h2>
{#users = db.relationship('User', backref='goods', secondary='user_goods')#}
<ul>
    {% for good in user.goods_list %}
        <li>{{ good }}--{{ good.price }}</li>
    {% endfor %}
</ul>
</body>
</html>

templates/goods/find_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--  要求当前页面使用IE浏览器最高版本的内核来渲染-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0">
    <meta charset="UTF-8">
    <title>find_user</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<h1>商品名:{{ goods.goods_name }}</h1>
<h1>价格:￥{{ goods.price }}</h1>
<hr>
<h2>购买此商品的用户的有</h2>
{{ goods.users }}
<ul>
{#users = db.relationship('User', backref='goods')#}
{% for user in goods.users %}
    <li><a href="{{ url_for('goods.find_goods', user_id=user.id) }}">{{ user.username }}</a></li>
{% endfor %}
</ul>


</body>
</html>

templates/goods/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--  要求当前页面使用IE浏览器最高版本的内核来渲染-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0">
    <meta charset="UTF-8">
    <title>购物页面</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<form action="{{ url_for('goods.buy') }}">
    <p>
        <select name="user_id" id="" class="form-control">
            <option value="0">请选择购物用户</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </p>
    <p>
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>序号</th>
            <th>商品</th>
            <th>价格</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for goods in goods_list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('goods.find_user', goods_id=goods.id) }}">{{ goods.goods_name }}</a></td>
            <td>{{ goods.price }}</td>
            <td>
                <input type="button" class="btn btn-primary" value="购买" tag="{{ goods.id }}">
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </p>
</form>
<script src="/js/jquery.min.js"></script>
<script>
$('.btn').click(function() {
    let goods_id = $(this).attr('tag');
    let user_id = $('select[name="user_id"]').val();
    console.log(goods_id, user_id);
    location.href = `{{ url_for('goods.buy') }}?user_id=${user_id}&goods_id=${goods_id}`;
})
</script>
</body>
</html>

templates/goods/user_goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--  要求当前页面使用IE浏览器最高版本的内核来渲染-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0">
    <meta charset="UTF-8">
    <title>user_goods</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<table class="table table-bordered table-striped table-hover">
    <thead>
    <tr>
        <th>序号</th>
        <th>用户id</th>
        <th>商品id</th>
        <th>购买数量</th>
    </tr>
    </thead>
    <tbody>
    {% for u in u_g %}
        <tr>
        <td>{{ loop.index }}</td>
        <td>{{ u.user_id }}</td>
        <td>{{ u.goods_id }}</td>
        <td>{{ u.number }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>