apps/articles/models.py
import datetime

from extends import db


class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_name = db.Column(db.String(20), nullable=False)
    articles = db.relationship('Article', backref='type')

    __table_rgs = {
        'extend_existing': True,
        'mysql_charset': 'utf-8'
    }

    def __str__(self):
        return self.type_name


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False)
    content = db.Column(db.BLOB, nullable=False)
    publish_date = db.Column(db.DateTime, default=datetime.datetime.now)
    click_num = db.Column(db.Integer, default=0)
    save_num = db.Column(db.Integer, default=0)
    love_num = db.Column(db.Integer, default=0)
    # 建立外键关系
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    type_id = db.Column(db.Integer, db.ForeignKey('article_type.id'), nullable=False)
    comments = db.relationship('Comment', backref='article')

    __table_args = {
        'extend_existing': True,
        'mysql_charset': 'utf-8'
    }

    def __str__(self):
        return self.title


class Comment(db.Model):
    # 自定义表名
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    comment = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    comment_date = db.Column(db.DateTime, default=datetime.datetime.now)

    __table_args = {
        'extend_existing': True,
        'mysql_charset': 'utf8'
    }

    def __str__(self):
        return self.comment

apps/articles/views.py
from flask import Blueprint, request, session, g, redirect, url_for, render_template, jsonify, session
from apps.articles.models import Article, ArticleType, Comment
from apps.users.models import User
from extends import db

article_bp = Blueprint('article', __name__)


@article_bp.route('/publish', methods=['POST', 'GET'], endpoint='publish')
def publish_article():
    if request.method == 'POST':
        article_dic = {
            'title': request.form.get('title'),
            'content': request.form.get('content').encode('utf-8'),
            'type_id': request.form.get('type'),
            'user_id': g.user.id,
        }
        article = Article(**article_dic)
        db.session.add(article)
        db.session.commit()
        return redirect(url_for('user.index'))


@article_bp.route('/detail', endpoint='detail')
def article_detail():
    article_id = request.args.get('article_id')
    article = Article.query.get(article_id)
    types = ArticleType.query.all()
    user_id = session.get('user_id')  # 登录用户
    user = None
    if user_id:
        user = User.query.get(user_id)
    # 单独查询评论
    page = int(request.args.get('page', 1))
    pagination = Comment.query.filter(Comment.article_id == article_id).order_by(-Comment.comment_date).paginate(page=page, per_page=5)
    return render_template('article/detail.html', article=article, types=types, user=user, pagination=pagination)


@article_bp.route('/save', endpoint='save')
def article_love():
    article_id = request.args.get('article_id')
    tag = request.args.get('tag')
    article = Article.query.get(article_id)
    if tag == '1':
        article.save_num -= 1
    else:
        article.save_num += 1
    db.session.commit()
    return jsonify(num=article.save_num)


@article_bp.route('/love', endpoint='love')
def article_love():
    tag = request.args.get('tag')
    article_id = request.args.get('article_id')
    article = Article.query.get(article_id)
    if tag == '1':
        article.love_num -= 1
    else:
        article.love_num += 1
    db.session.commit()
    return jsonify(num=article.love_num)


@article_bp.route('/add_comment', methods=['GET', 'POST'])
def article_comment():
    if request.method == 'POST':
        comment_dic = {
            'comment': request.form.get('comment'),
            'user_id': g.user.id,
            'article_id': request.form.get('aid')
        }
        comment = Comment(**comment_dic)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('article.detail', article_id=comment_dic.get('article_id')))
    return redirect(url_for('user.index'))


@article_bp.route('/type_search')
def type_search():
    user_id = session.get('user_id')
    user = None
    if user_id:
        user = User.query.get(user_id)
    types = ArticleType.query.all()
    type_id = request.args.get('type_id', 1)
    article_type = ArticleType.query.get(type_id)

    return render_template('article/article_type.html', user=user, types=types, article_type=article_type)

templates/article/add_article.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>添加文章</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<form action="{{ url_for('article.publish') }}" method="post">
    <p><input type="text" name="title" placeholder="文章标题" class="form-control"></p>
    <p>
        <textarea placeholder="输入文章内容" id="" cols="30" rows="10" class="form-control" name="content"></textarea>
    </p>
    <p>
        <select name="user_id" id="" class="form-control">
            <option value="0">请选择用户</option>
            {% for user in users %}

                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </p>
    <p><input type="submit" value="添加文章" class="btn btn-primary"></p>
</form>
</body>
</html>

templates/article/all.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>文章首页</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
{% for article in articles %}
    <div class="row">
    <p>
    <h3>{{ article.title }}</h3>
                {# 反向解析 article.user   articles = db.relationship('Article', backref='user')     #}
        {#  根据文章找用户反向引用      #}
        <div>作者:{{ article.user.username }}</div>
    </p>
    <p>
        {{ article.content }}
    </p>
    <div>{{ article.publish_date }}</div>
    </div>
    <hr color="blue">
{% endfor %}
</div>
</body>
</html>

templates/article/all1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>用户所有文章</title>
    <link rel="stylesheet" href="/css/bootstrap-3.3.7-dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
                {# 通过用户找文章正向引用 articles = db.relationship('Article', backref='user')#}
    {{ user.articles }}
    {% for article in user.articles %}
        <div class="row">
            <p>
                <h3>{{ article.title }}</h3>
            <div>作者: {{ user.username }}</div>
            </p>
        <p>
            {{ article.content }}
        </p>
        <div>{{ article.publish_date }}</div>
        </div>
    {% endfor %}
</div>
</body>
</html>

templates/article/article_type.html
{% extends 'base.html' %}
{% block title %}
    文章分类
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        .article {
            width: 90%;
            margin: 20px auto;
            padding: 5px 10px;
            background-color: rgba(131, 202, 227, 0.7);
            border-bottom: 1px solid gray;
        }

        .article p {
            font-size: 14px;
        rgba(75, 75, 74, 1.00);
        }

        .article h4 a {
            color: rgba(80, 80, 79, 1.00);
        }

        .article h4 a:hover {
            color: black;
        }

        .article div span {
            margin-left: 20px;
        }

        .article div {
            margin-bottom: 18px;
        }

    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        {% for article in article_type.articles %}
            <div class="article">
                <h4><a href="{{ url_for('article.detail', article_id=article.id) }}">{{ article.title }}</a></h4>
                <p>
                    <span>作者:{{ article.user.username }}</span>
                    <br>
                    <br>
                <div>{{ article.content | cdecode | safe }}</div>
                </p>
                <div>
                    <span style="margin-left: 0">发布时间：{{ article.publish_date }}</span>
                    <span>收藏:{{ article.save_num }}</span><span>点击量:{{ article.click_num }}</span><span>点赞量:{{ article.love_num }}</span>
                </div>
            </div>

        {% endfor %}
{#        <nav aria-label="Page navigation" class="col-md-offset-5">#}
{#                <ul class="pagination">#}
{#                    <li {% if not pagination.has_prev %}class="disabled"{% endif %}><a href="{{ url_for('user.index', page=pagination.prev_num) }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>#}
{#                    {% for page_num in range(1, pagination.pages + 1) %}#}
{#                        <li {% if pagination.page== page_num %} class="active" {% endif %}><a href="{{ url_for('user.index', page=page_num) }}">{{ page_num }}</a></li>#}
{#                    {% endfor %}#}
{##}
{#                    <li {% if not pagination.has_next %}class="disabled" {% endif %}><a href="{{ url_for('user.index', page=pagination.next_num) }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>#}
{#                </ul>#}
{#            </nav>#}
    </div>
{% endblock %}

templates/article/detail.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    #container {
        width: 1200px;
        margin: 0 auto;
    }
     #detail {
            background-color: rgba(232, 243, 242, 0.6);
            border-radius: 10px;
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px 50px;
        }

        #detail h2 {
            text-align: center;
        }

        #detail h2 + div {
            height: 30px;
            line-height: 30px;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }

        .item {
            overflow: auto;
            border-bottom: 1px solid lightgray;
            margin-bottom: 20px;
            padding: 10px;
        }

        #item_left {
            float: left;
            width: 10%;
            text-align: center;
        }

        #item_left img {
            width: 50px;
            height: 50px;
            border-radius: 25px;
        }

        #item_right {
            float: right;
            width: 90%;
        }

        textarea {
            resize: none;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <p>
                作者: {{ article.user.username }} &nbsp;&nbsp;&nbsp;&nbsp;
                发布时间: {{ article.publish_date }} &nbsp;&nbsp;&nbsp;&nbsp;
            </p>
            <div>
                {{ article.content | cdecode | safe }}
            </div>
            <div>
                    <button type="button" class="btn btn-primary" aria-label="Left Align">
                      <span class="glyphicon glyphicon-heart" aria-hidden="true" tag="0">&nbsp;{{ article.save_num }}</span>
                    </button>
                    <button type="button" class="btn btn-danger" aria-label="Left Align">
                      <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true" tag="0">&nbsp;{{ article.love_num }}</span>
                    </button>
            </div>
            <hr>
            <div id="comment">
                <p>文章评论:</p>
                <div>
                    <form action="{{ url_for('article.article_comment') }}" method="post">
                        <input type="hidden" name="aid" value="{{ article.id }}">
                        <p>
                    <textarea name="comment" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                        </p>
                        <p><input type="submit" value="评论" class="btn btn-info"></p>
                    </form>
                </div>
                <p style="margin: 20px 5px; border-bottom: 1px solid lightgray">

                </p>
                <div id="comment_item">
                {% if pagination.items%}
                    {% for comment in pagination.items %}
                        <div class="item">
                            <div id="item_left">
                                <img src="{% if comment.user.icon %}{{ url_for('static', filename=comment.user.icon) }}{% else %}{{ url_for('static',filename='img/Erha.jpg') }}{% endif %}" alt="">
                            </div>
                            <div id="item_right">
                                <p>
                                    <span>{{ comment.user.username }}</span>
                                    <span>{{ comment.comment_date }}</span>
                                </p>
                                <p>
                                    {{ comment.comment }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                        <div class="item">
                            当前文章还没有任何评论，赶快发表意见吧~~~~~
                        </div>
                {% endif %}

                </div>
                <div id="paginate">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li class="previous {% if not pagination.has_prev %} disabled {% endif %}"><a
                                    href="{{ url_for('article.detail', page=pagination.prev_num, article_id=article.id) }}"><span
                                    aria-hidden="true">&larr;</span> 上一页</a></li>

                            <li class="next {% if not pagination.has_next %} disabled {% endif %}"><a
                                    href="{{ url_for('article.detail', page=pagination.next_num, article_id=article.id) }}">下一页
                                <span
                                        aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 点赞
            $('.btn-danger').click(function() {
                let $this = $(this);
                let tag = $this.children('span').attr('tag');
                $.get('{{ url_for('article.love') }}', {article_id: {{ article.id }}, tag:tag }, function(data) {
                    // $('.heart').text(data.num).prev('span').css({'color': 'red'});
                    $this.children('span').text(`  ${data.num}`);
                    // $this.css({'color': 'red'});
                });
                if(tag === '1') {
                    $this.children('span').css({'color': ''});
                    $this.children('span').attr('tag', '0');
                } else {
                    $this.children('span').css({'color': 'blue'});
                    $this.children('span').attr('tag', '1');
                }
            });
            // 收藏
            $('.btn-primary').click(function() {
                let $this = $(this);
                let tag = $this.children('span').attr('tag');
                $.get('{{ url_for('article.save') }}', {article_id: {{ article.id }}, tag: tag}, function(data) {
                    // $('.heart').text(data.num).prev('span').css({'color': 'red'});
                    $this.children('span').text(`  ${data.num}`);
                    // $this.css({'color': 'red'});
                });
                if(tag === '1') {
                    $this.children('span').css({'color': ''});
                    $this.children('span').attr('tag', '0');
                } else {
                    $this.children('span').css({'color': 'red'});
                    $this.children('span').attr('tag', '1');
                }

            });
            $('[name="comment"]').focus(function() {
               $(this).text("")
            });
        });
    </script>
{% endblock %}

templates/article/detail1.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        #detail {
            background-color: rgba(232, 243, 242, 0.6);
            border-radius: 10px;
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px 50px;
        }

        #detail h2 {
            text-align: center;
        }

        #detail h2 + div {
            height: 30px;
            line-height: 30px;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }

        .item {
            overflow: auto;
            border-bottom: 1px solid lightgray;
            margin-bottom: 20px;
            padding: 10px;
        }

        #item_left {
            float: left;
            width: 10%;
            text-align: center;
        }

        #item_left img {
            width: 50px;
            height: 50px;
            border-radius: 25px;
        }

        #item_right {
            float: right;
            width: 90%;
        }

    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <div>
                <div id="left">作者:{{ article.user.username }} &nbsp;&nbsp;&nbsp; &nbsp;
                    发布时间: {{ article.pdatetime }}</div>
                <div id="right">
                    <span class="glyphicon glyphicon-heart"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.save_num }}</span>
                    &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
                    <span class="glyphicon glyphicon-thumbs-up"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.love_num }}</span>
                </div>
            </div>
            <div id="content">
                {{ article.content|cdecode|safe }}
            </div>
            <hr>
            <div id="comment">
                <p>文章评论:</p>
                <div>
                    <form action="{{ url_for('article.article_comment') }}" method="post">
                        <input type="hidden" name="aid" value="{{ article.id }}">
                        <p>
                    <textarea name="comment" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                        </p>
                        <p><input type="submit" value="评论" class="btn btn-info"></p>
                    </form>
                </div>
                <p style="margin: 20px 5px; border-bottom: 1px solid lightgray">

                </p>
                <div id="comment_item">
                    {% if comments.items %}
                        {% for comment in comments.items %}
                            <div class="item">
                                <div id="item_left">
                                    <img src=" {% if comment.user.icon %} {{ url_for('static',filename=comment.user.icon) }} {% else %}{{ url_for('static',filename='images/touxiang.jpg') }}{% endif %}"
                                         alt="">
                                </div>
                                <div id="item_right">
                                    <p>
                                        <span>{{ comment.user.username }}</span>
                                        <span>{{ comment.cdatetime }}</span>
                                    </p>
                                    <p>
                                        {{ comment.comment }}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="item">
                            当前文章还没有任何评论，赶快发表意见吧～～～～
                        </div>
                    {% endif %}
                </div>
                <div id="paginate">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li class="previous {% if not comments.has_prev %}disabled{% endif %}"><a
                                    href="{{ url_for('article.article_detail') }}?page={{ comments.prev_num }}&aid={{ article.id }}"><span
                                    aria-hidden="true">&larr;</span> 上一页</a></li>

                            <li class="next {% if not comments.has_next %}disabled {% endif %}"><a
                                    href="{{ url_for('article.article_detail') }}?page={{ comments.next_num }}&aid={{ article.id }}">下一页
                                <span
                                        aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 收藏
            $('.glyphicon-heart').click(function () {

            });
            // 点赞
            $('.glyphicon-thumbs-up').click(function () {

                let $this = $(this);
                let tag = $this.next('span').attr('tag');

                $.get('{{ url_for('article.article_love') }}', {aid:{{article.id}}, tag: tag}, function (data) {
                    $this.next('span').text(data.num);

                });
                if (tag == 1) {
                    $this.css({'color': 'black'});
                    $this.next('span').attr('tag', "0");
                } else {
                    $this.css({'color': 'red'});
                    $this.next('span').attr('tag', "1");
                }


            });
            //文本域
            $('textarea[name="comment"]').focus(function () {
                $(this).val("")
            })

        })
    </script>
{% endblock %}

templates/article/detail2.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }

        #detail {
            background-color: rgba(232, 243, 242, 0.6);
            border-radius: 10px;
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px 50px;
        }

        #detail h2 {
            text-align: center;
        }

        #detail h2 + div {
            height: 30px;
            line-height: 30px;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }

        .item {
            overflow: auto;
            border-bottom: 1px solid lightgray;
            margin-bottom: 20px;
            padding: 10px;
        }

        #item_left {
            float: left;
            width: 10%;
            text-align: center;
        }

        #item_left img {
            width: 50px;
            height: 50px;
            border-radius: 25px;
        }

        #item_right {
            float: right;
            width: 90%;
        }

    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">
            <h2>{{ article.title }}</h2>
            <div>
                <div id="left">作者:{{ article.user.username }} &nbsp;&nbsp;&nbsp; &nbsp;
                    发布时间: {{ article.pdatetime }}</div>
                <div id="right">
                    <span class="glyphicon glyphicon-heart"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.save_num }}</span>
                    &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
                    <span class="glyphicon glyphicon-thumbs-up"
                          aria-hidden="true"></span>&nbsp;&nbsp;<span tag="0">{{ article.love_num }}</span>
                </div>
            </div>
            <div id="content">
                {{ article.content|cdecode|safe }}
            </div>
            <hr>
            <div id="comment">
                <p>文章评论:</p>
                <div>
                    <p>
                    <textarea name="content" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                    </p>
                    <p><input type="button" value="评论" class="btn btn-info"></p>

                </div>
                <p style="margin: 20px 5px; border-bottom: 1px solid lightgray">

                </p>
                <div id="comment_item">
                    <div class="item">
                        <div id="item_left">
                            <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="">
                        </div>
                        <div id="item_right">
                            <p>
                                <span>匿名用户</span>
                                <span>2020-05-31 12:30:55</span>
                            </p>
                            <p>
                                很喜欢你的博客文章，加油啊！
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div id="item_left">
                            <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="">
                        </div>
                        <div id="item_right">
                            <p>
                                <span>匿名用户</span>
                                <span>2020-05-31 12:30:55</span>
                            </p>
                            <p>
                                很喜欢你的博客文章，加油啊！
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div id="item_left">
                            <img src="{{ url_for('static',filename='images/touxiang.jpg') }}" alt="">
                        </div>
                        <div id="item_right">
                            <p>
                                <span>匿名用户</span>
                                <span>2020-05-31 12:30:55</span>
                            </p>
                            <p>
                                很喜欢你的博客文章，加油啊！
                            </p>
                        </div>
                    </div>
                </div>
                <div id="paginate">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> Older</a>
                            </li>
                            <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>

                </div>
            </div>

        </div>

    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            // 收藏
            $('.glyphicon-heart').click(function () {

            });
            // 点赞
            $('.glyphicon-thumbs-up').click(function () {

                let $this = $(this);
                let tag = $this.next('span').attr('tag');

                $.get('{{ url_for('article.article_love') }}', {aid:{{article.id}}, tag: tag}, function (data) {
                    $this.next('span').text(data.num);

                });
                if (tag == 1) {
                    $this.css({'color': 'black'});
                    $this.next('span').attr('tag', "0");
                } else {
                    $this.css({'color': 'red'});
                    $this.next('span').attr('tag', "1");
                }


            });
            //文本域
            $('textarea[name="content"]').focus(function () {
                $(this).val("")
            })

        })
    </script>
{% endblock %}