apps/users/models.py
import datetime

from extends import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(32), nullable=False)
    password = db.Column(db.String(101), nullable=False)
    phone = db.Column(db.String(11), nullable=False, unique=True)
    email = db.Column(db.String(30))
    icon = db.Column(db.String(100))
    is_delete = db.Column(db.Boolean, default=False)
    register_time = db.Column(db.DateTime, default=datetime.datetime.now)
    # 增加一个字段，不会出现在数据库中,relationship()是在view和template中体现价值的
    #                                      backref:反向引用，通过文章找user
    # lay决定了sqlalchemy什么时候从数据库中加载数据，dynamic在有多条数据的时候特别有用，不是直接加载这些数据
    # 默认是select
    articles = db.relationship('Article', backref='user')
    comments = db.relationship('Comment', backref='user')
    __table_args__ = {
        'extend_existing': True,
        'mysql_charset': 'utf8'
    }

    def __str__(self):
        return self.username


class Photo(db.Model):
    __tablename__ = 'photo'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    photo_name = db.Column(db.String(32), nullable=False)
    photo_datetime = db.Column(db.DateTime, default=datetime.datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    __table_args = {
        'extend_existing': True,
        'mysql_charset': 'utf-8'
    }

    def __str(self):
        return self.photo_name


class AboutMe(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.BLOB, nullable=False)
    pdatetime = db.Column(db.DateTime, default=datetime.datetime.now)
    # 与用户建立联系
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True)  # unique没有设置成True，查询出来的话会是一个列表，flask里的外键都是一对多
    user = db.relationship('User', backref='about')

    __table__args = {
        'extend_existing': True,
        'mysql_charset': 'urf-8'
    }

    def __str__(self):
        return self.user


class MessageBoard(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.String(255), nullable=False)
    mdatetime = db.Column(db.DateTime, default=datetime.datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='messages')

    __table__args = {
        'extend_existing': True,
        'mysql_charset': 'utf-8'
    }

    def __str__(self):
        return self.content

apps/users/views.py
import os
import time

from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, g
from sqlalchemy import and_
from werkzeug.utils import secure_filename
from apps.users.smssend import SmsSendAPIDemo

from apps.users.models import User, Photo, AboutMe, MessageBoard
from apps.articles.models import ArticleType, Article
from apps.utils.util import upload_qiniu, delete_qiniu, send_messages
from encryption import get_md5
from extends import db, cache
from settings import BaseConfig

user_bp = Blueprint('user', __name__, url_prefix='/user')

required_login_path = ['/user/center',
                       '/user/change',
                       '/article/publish',
                       '/user/upload_photo',
                       '/user/photo_del',
                       '/article/add_comment',
                       '/user/about_me',
                       '/user/show_about',
                       ]


@user_bp.before_app_first_request
def first_request():
    print('before_app_first_request')


@user_bp.before_app_request
def first_request1():
    print('before_first_request1:', request.path)
    if request.path in required_login_path:
        print('需要验证用户的登录情况')
        user_id = session.get('user_id')
        print(user_id)
        if not user_id:
            return render_template('user/login.html')
        else:
            user = User.query.get(user_id)
            # g对象，本次请求的对象，本次请求中产生的一个对象，存活周期只在这一次请求中
            g.user = user  # 给g对象添加一个user属性，属性值为 User.query.get(user_id)
            print('g:', g)


# 处理完了视图函数，拿到了一个返回值response对象
@user_bp.after_app_request
def after_request_test(response):
    response.set_cookie('username', 'AKW', max_age=19)
    print(response)
    print(request.cookies)
    return response


@user_bp.teardown_app_request
def teardown_request(response):
    return response


@user_bp.app_template_filter('cdecode')
def content_decode(content: bytes):
    content = content.decode('utf-8')
    return content[:200]


@user_bp.app_template_filter('cdecode1')
def content_decode1(content: bytes):
    return content.decode('utf-8')


@user_bp.route('/')
# @cache.cached(timeout=50)  # 缓存首页，50秒内返回首页时不需要发送请求
def index():
    print(request.cookies)
    # user_id = request.cookies.get('is_login', None)
    print('session:', session)

    user_id = session.get('user_id')
    print(user_id)
    # 接收页码数
    page = int(request.args.get('page', 1))
    pagination = Article.query.order_by(-Article.publish_date).paginate(page=page, per_page=3)  # 用于分页的函数paginate
    # Article.query.order_by(-Article.publish_date).all() 负号表示降序
    print(pagination.items)  # [<Article 4>, <Article 3>, <Article 2>],获取拿到的记录

    print(pagination.page)  # 当前的页码数
    print(pagination.prev_num)
    print(pagination.next_num)
    print(pagination.has_next)
    print(pagination.has_prev)
    print(pagination.pages)  # 总共可以分为几页
    print(pagination.total)  # 总共几条数据
    types = ArticleType.query.all()
    for i in range(10):
        time.sleep(0.5)
        if user_id:  # 判断用户是否登录
            user = User.query.get(user_id)
            return render_template('user/index.html', user=user, types=types, pagination=pagination)
        return render_template('user/index.html', types=types, pagination=pagination)


@user_bp.route('/register', endpoint='register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        # con_password = generate_password_hash(request.form.get('confirmPassword'))
        con_password = get_md5(request.form.get('confirmPassword'))
        user_dic = {
            'username': request.form.get('username'),
            'password': get_md5(request.form.get('password')),
            'phone': request.form.get('phone'),
            'email': request.form.get('email')
        }
        if con_password == user_dic.get('password'):
            user = User(**user_dic)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.login'))
        else:
            return redirect(url_for('user.register'))
    return render_template('user/register.html')


@user_bp.route('/login', endpoint='login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        f = request.args.get('f')
        if f == '1':
            username = request.form.get('username')
            password = get_md5(request.form.get('password'))
            users = User.query.filter(and_(User.username == username, User.password == password)).all()
            for user in users:
                if user:
                    # response = redirect(url_for('user.index'))
                    # response.set_cookie('is_login', value=str(user.id), max_age=600000)
                    # print(response)
                    # return response
                    session['user_id'] = user.id
                    print('session:', session)
                return redirect(url_for('user.index'))
            else:
                return render_template('user/login.html', msg='用户名或密码有误')
        elif f == '2':
            phone = request.form.get('phone')
            code = request.form.get('code')
            print('session:code:', session, code)
            # 先验证验证码
            valid_code = cache.get(phone)
            if code == valid_code:
                user = User.query.filter(User.phone == phone).first()
                if user:
                    # 登录成功, 记录登录成功的状态
                    session['user_id'] = user.id
                    return redirect(url_for('user.index'))
                else:
                    return render_template('user/login.html', msg='此号码未注册')
            else:
                return render_template('user/login.html', msg='验证码有误!')
    return render_template('user/login.html')


# 手机号码验证
@user_bp.route('/check_phone', endpoint='check', methods=['GET', 'POST'])
def check_phone():
    phone = request.args.get('phone')
    user = User.query.filter(User.phone == phone).all()
    # code: 400 不能用  200 可以用
    if len(user) > 0:
        return jsonify(code=400, msg='此手机号码以被注册')
    else:
        return jsonify(code=200, msg='此号码可以用')


@user_bp.route('/send_msg', endpoint='send_msg')
def send_message():
    phone = request.args.get('phone')
    """示例代码入口"""
    ret, code = send_messages(phone)
    print('ret:ret:ret:ret:ret:ret:ret:ret:', ret, code)
    if ret is not None:
        if ret['code'] == 405:
            # 存到缓存redis
            # cache.set(key, value, timeout=second)
            cache.set(phone, code, timeout=180)
            return jsonify(code=ret['code'], msg=f'验证码为{code}，请在3分钟之内填写，短信服务尚未通过审核，敬请谅解')
        else:
            print(f'ERROR: ret.code={ret["code"]},msg={ret["msg"]}')
            return jsonify(code=400, msg='短信发送失败')


@user_bp.route('/logout', endpoint='logout')
def logout():
    # 通过response对象删除cookie
    # response = redirect(url_for('user.index'))
    # print(response)
    # response.delete_cookie('is_login')
    del session['user_id']  # 指回删除session中的这个键值对  不会删除session空间和cookie
    session.clear()  # session.clear() 删除session的内存空间和删除cookie
    return redirect(url_for('user.index'))


# 用户中心
@user_bp.route('/center', endpoint='center')
def user_center():
    types = ArticleType.query.all()
    photos = Photo.query.filter(Photo.user_id == g.user.id).all()
    return render_template('user/center.html', user=g.user, types=types, photos=photos)


# 图片扩展名
ALLOWED_EXTENSIONS = ['jpg', 'png', 'gif', 'bmp']


# 用户信息修改
@user_bp.route('/change', methods=['GET', 'POST'], endpoint='change')
def user_change():
    if request.method == 'POST':
        icon = request.files.get('icon')
        icon_name = icon.filename
        suffix = icon_name.rsplit('.')[-1]
        if suffix in ALLOWED_EXTENSIONS:
            icon_name = secure_filename(icon_name)  # 保证文件名是符合python的命名规则
            file_path = os.path.join(BaseConfig.UPLOAD_ICON_DIR, icon_name)
            icon.save(file_path)
            path = 'upload/icon/'

            username = request.form.get('username')
            phone = request.form.get('phone')
            email = request.form.get('email')

            user = g.user
            user.username = username
            user.phone = phone
            user.email = email
            user.icon = os.path.join(path, icon_name)
            db.session.commit()
            return redirect(url_for('user.center'))
        else:
            return render_template('user/center.html', user=g.user, msg='请上传图片，格式为jpg,png,bmp,gif')
        # 判断手机号是否已注册或被使用
        # users = User.query.all()
        # for user in users:
        #     if user.phone == phone:
        #         # 改号码已被使用
        #         return render_template('user/center.html', user=g.user, msg='此号码已被使用')

    return render_template('user/center.html', user=g.user, types=ArticleType.query.all())


@user_bp.route('/upload_photo', methods=['GET', 'POST'])
def upload_photo():
    # 获取上传的内容
    photo_file = request.files.get('photo')
    print(photo_file)
    ret, info = upload_qiniu(photo_file)
    key = ret['key']
    if info.status_code == 200:
        photo_dic = {
            'photo_name': key,
            'user_id': g.user.id
        }
        photo = Photo(**photo_dic)
        db.session.add(photo)
        db.session.commit()
        return '上传成功'
    else:
        return '上传失败'


# 删除相册图片
@user_bp.route('/photo_del')
def photo_del():
    pid = request.args.get('pid')
    photo = Photo.query.get(pid)
    ret, info = delete_qiniu(photo)
    if info.status_code == 200:
        # 删除数据库中的图片
        db.session.delete(photo)
        db.session.commit()
        return redirect(url_for('user.center'))
    else:
        refer = request.referrer  # 也可以通过request.headers.get('Referer', None) 获取
        print(refer)
        return render_template('500.html', err_msg='删除相册图片失败', refer=refer)


@user_bp.route('/myphoto')
def myphoto():
    print('referer:', request.referrer)
    page = int(request.args.get('page', 1))

templates/user/about_me.html
{% extends 'base.html' %}
{% block title %}
    关于我
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1200px;
            margin: 0 auto;
        }
        #container p {
            width: 80%;
            background-color: #83cae3;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        {% if user.about %}
            {% for about in user.about %}
            <p>
                {{ about.content | cdecode1 | safe }}
            </p>
            {% endfor %}
            {% else %}
            还没有设关于我呢，去用户中心设置吧
        {% endif %}

    </div>
{% endblock %}

templates/user/board.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    #container {
        width: 1200px;
        margin: 0 auto;
    }
     #detail {
            background-color: rgba(232, 243, 242, 0.6);
            border-radius: 10px;
            margin-top: 20px;
            margin-bottom: 20px;
            padding: 20px 50px;
        }

        #detail h2 {
            text-align: center;
        }

        #detail h2 + div {
            height: 30px;
            line-height: 30px;
        }

        #left {
            float: left;
        }

        #right {
            float: right;
            margin-right: 30px;
        }

        #content {
            margin-top: 30px;
        }

        .item {
            overflow: auto;
            border-bottom: 1px solid lightgray;
            margin-bottom: 20px;
            padding: 10px;
        }

        #item_left {
            float: left;
            width: 10%;
            text-align: center;
        }

        #item_left img {
            width: 50px;
            height: 50px;
            border-radius: 25px;
        }

        #item_right {
            float: right;
            width: 90%;
        }

        textarea {
            resize: none;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="detail">

            <div id="comment">
                <p>用户留言:</p>
                <div>
                    <form action="{{ url_for('user.show_board') }}" method="post">
                        <input type="hidden" name="aid" value="">
                        <p>
                    <textarea name="board" class="form-control" style="width: 60%" rows="5" cols="60">写下你想说的，开始我们的对话
                    </textarea>
                        </p>
                        <p><input type="submit" value="发表留言" class="btn btn-info"></p>
                    </form>
                </div>
                <p style="margin: 20px 5px; border-bottom: 1px solid lightgray">

                </p>
                <div id="comment_item">
                {% if boards %}
                    {% for board in boards.items %}
                        <div class="item">
                                <div id="item_left">
                                    <img src="{% if board.user.icon %}{{ url_for('static', filename=board.user.icon) }}{% else %}{{ url_for('static',filename='img/Erha.jpg') }}{% endif %}" alt="">
                                </div>
                                <div id="item_right">
                                    <p>
                                        <span>
                                            {% if board.user.username %}
                                                {{ board.user.username }}
                                                {% else %}
                                                匿名用户
                                            {% endif %}
                                        </span>
                                        <span>{{ board.mdatetime }}</span>
                                    </p>
                                    <p>
                                        {{ board.content }}
                                    </p>
                                </div>
                            </div>
                    {% endfor %}
                    {% else %}
                        <div class="item">
                            当前文章还没有任何评论，赶快发表意见吧~~~~~
                        </div>
                {% endif %}
                </div>
                <div id="paginate">
                    <nav aria-label="...">
                        <ul class="pager">
                            <li class="previous {% if not boards.has_prev %} disabled {% endif %}"><a
                                    href="{{ url_for('user.show_board', page=boards.prev_num) }}"><span
                                    aria-hidden="true">&larr;</span> 上一页</a></li>

                            <li class="next {% if not boards.has_next %} disabled {% endif %}"><a
                                    href="{{ url_for('user.show_board', page=boards.next_num) }}">下一页
                                <span
                                        aria-hidden="true">&rarr;</span></a></li>
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {

            $('[name=board]').focus(function() {
               $(this).text("")
            });
        });
    </script>
{% endblock %}

templates/user/center.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/center.css') }}">
    <style>
        th {
            text-align: center;
        }
        a {
            text-decoration: none;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
            <p>管理相册</p>
            <p>管理留言</p>
            <p>关于我设置</p>
        </div>
        <div id="right">
            <div class="right1">
                <h2> 用户信息修改</h2>
                <form action="{{ url_for('user.change') }}" method="post" enctype="multipart/form-data">
                    <p><input type="text" class="form-control" id="InputUsername" name="username"
                              value="{{ g.user.username }}">
                    </p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone"
                              value="{{ g.user.phone }}"><span></span>
                    </p>
                    <p><input type="email" class="form-control" id="InputEmail1" name="email"
                              value="{{ g.user.email }}">
                    </p>
                    <p><input type="file" id="exampleInputFile" name="icon"></p>
                    <p>
                        <img src="{% if g.user.icon %} {{ url_for('static',filename=user.icon) }} {% else %}{{ url_for('static',filename='img/Erha.jpg') }}{% endif %}"
                             alt="" width="90"
                             height="100">
                    </p>
                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>

                </form>
            </div>
            <div class="right1" style="padding-top: 20px">
                <form action="{{ url_for('article.publish') }}" method="post">
                    <p><input type="text" class="form-control" id="InputTitle" name="title"
                              placeholder="请输入文章标题">
                    </p>
                    <p>
                        <select name="type" class="form-control">
                            <option value="0">请选择文章分类</option>
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.type_name }}</option>
                            {% endfor %}

                        </select>
                    </p>
                    <p>
                        <textarea name="content" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">发表文章</button>
                    </p>

                </form>
            </div>
            <div class="right1">
                <form action="{{ url_for('user.upload_photo') }}" method="post" enctype="multipart/form-data" class="form-inline">
                    <input type="file" name="photo" class="form-control">
                    <input type="submit" value="上传相册" class="btn btn-default">
                </form>
                <div class="row">
                    <div class="col-sm-12">
                        <h3>我的相册</h3>
                        <div class="row">
                            {% for photo in photos %}
                            <div class="col-xs-8 col-sm-4">
                                <img src="http://qmvgt21j4.hn-bkt.clouddn.com/{{ photo.photo_name }}" alt="..." class="img-rounded image">
                                <button class="btn btn-info btn-xs photo-del" tag="{{ photo.id }}">删除</button>
                            </div>

                            {% endfor %}


                        </div>
                    </div>
                </div>

            </div>
            <div class="right1" style="padding-top: 30px">
                {% if user.messages %}
                <table class="table table-hover table-striped table-bordered">
                    <tr>
                        <th>序号</th>
                        <th>留言</th>
                        <th>时间</th>
                        <th>操作</th>
                    </tr>
                    {% for message in user.messages %}
                        <tr {% if loop.index%2==0 %}class="info"{% endif %}>
                            <td>{{ loop.index }}</td>
                            <td>{{ message.content }}</td>
                            <td>{{ message.mdatetime }}</td>
                            <td><a href="{{ url_for('user.delete_board', bid=message.id) }}">删除留言</a></td>
                        </tr>
                    {% endfor %}

                </table>
                    {% else %}
                    <p>还没有任何留言，去留言板发表吧!</p>
                {% endif %}
            </div>
            <div class="right1" style="padding-top: 30px">
                <form action="{{ url_for('user.about') }}" method="post" enctype="multipart/form-data">
                    <p>
                        <textarea name="about" class="mytextarea">

                        </textarea>
                    </p>
                    <p></p>
                    <p style="text-align: right;">
                        <button type="submit" class="btn btn-primary">更改我的</button>
                    </p>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static',filename='tinymce/tinymce.min.js') }}"></script>
    <script>
        $(function () {
    //设置富文本
    tinymce.init({
        selector: '.mytextarea',
        height: 400,
        plugins: "quickbars emoticons",
        inline: false,
        toolbar: true,
        menubar: true,
        quickbars_selection_toolbar: 'bold italic | link h2 h3 blockquote',
        quickbars_insert_toolbar: 'quickimage quicktable',

    });
    //验证手机号码
    $('#InputPhone').blur(function () {
        let phone = $(this).val();
        let span_ele = $(this).next('span');
        if (phone.length == 11) {
            span_ele.text('');
            $.get('{{ url_for("user.check") }}', {phone: phone}, function (data) {
                // {#console.log(data);#}
                if (data.code != 200) {
                    span_ele.css({"color": "#ff0011", "font-size": "12px"});
                    span_ele.text(data.msg);
                }
            }
        )
        } else {
            span_ele.css({"color": "#ff0011", "font-size": "12px"});
            span_ele.text('手机格式错误');
        }

    });
    $('.right1').hide();
    $('.right1').eq(0).show();
    $("#left p").first().css({'background-color': 'rgba(30, 150, 196, 0.94)'});
    //切换右侧div
    $("#left p").each(function (i) {
        $(this).click(function () {
            $("#left p").css({'background-color': 'rgba(30, 150, 196, 0.94)'});
            $(this).css({'background-color': 'skyblue', 'box-shadow': '5px 5px 5px deepskyblue'});
            $('.right1').hide();
            $('.right1').eq(i).show();
        });
    });
    // 相册图片的删除
            $('.photo-del').click(function() {
                // 获取属性值tag，tag属性就是图片的主键值
                let flag = confirm('确定删除此图片吗?');
                if (flag) {
                    let pid = $(this).attr('tag');
                    location.href = '{{ url_for('user.photo_del') }}?pid=' + pid;
                }

            });
})
    </script>
{% endblock %}

templates/user/center1.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
            margin-bottom: 50px;
        }

        #container div {
            float: left;
        }

        #left {
            width: 30%;
            height: 600px;
            background-color: skyblue;
        }

        #left p {
            margin-top: 40px;
            border: 1px solid lightgray;
            border-radius: 5px;
            text-align: center;
            font-size: 20px;
            color: white;
            padding: 10px;
            cursor: default;
        }


        #right {
            width: 70%;
            height: 600px;
            background-color: skyblue;
            opacity: 0.5;
        }

        #right1 {
            text-align: center;
            padding-left: 120px;
            padding-top: 100px;
        }

        #right1 p {
            margin: 20px auto;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div id="left">
            <p>用户信息修改</p>
            <p>发表文章</p>
        </div>
        <div id="right">
            <div id="right1">
                <h2> 用户信息修改</h2>                                    <!--enctype相当于一种编码方式，要求与图片的编码方式相同-->
                <form action="{{ url_for('user.change') }}" method="post" enctype="multipart/form-data">
                    <p><input type="text" class="form-control" id="InputUsername" name="username" value="{{ user.username }}">
                    </p>
                    <p><input type="text" class="form-control" id="InputPhone" name="phone" value="{{ user.phone }}">
                        <span></span>
                    </p>
                    <p><input type="email" class="form-control" id="InputEmail1" name="email" value="{{ user.email }}">
                    </p>
                    <p><input type="file" id="exampleInputFile" name="icon"></p>
                    <p>
                        <img src="{{ url_for('static', filename='img/胖丁.jpg') }}" alt="" width="100">
                    </p>
                    <p>
                        <button type="submit" class="btn btn-primary">用户信息修改</button>
                    </p>

                </form>
            </div>
            <div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
         $('#inputPhone').blur(function () {
            let phone = $(this).val();
            if (phone.length === 11) {
                $(this).next('span').text('')
                // jQuery[ method ] = function( url, data, callback, type ) {
                $.get('{{ url_for('user.check') }}', {phone: phone}, function (data) {
                    console.log(data, this);
                    if (data.code !== 200) {
                        $('#inputPhone').next('span').text(data.msg).css({color: '#ff0011', 'font-size': '12px'})
                    }
                });
            } else {
                $(this).next('span').text('请输入正确的手机号').css({color: '#ff0011', 'font-size': '12px'})
            }
        });
    </script>
{% endblock %}

templates/user/index1.html
{% extends 'base.html' %}
{% block title %}
    博客首页
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            margin: 0 auto;
        }
        .article {
            width: 900px;
            background-color: blueviolet;
            margin-bottom: 20px;
            border: 1px solid gray;
        }
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
        {% for article in articles %}
            <div class="article">
                <h1>{{ article.title }}</h1>
                <p>{{ article.content }}</p>
                <h6>发布时间:{{ article.publish_date }}</h6>
                <h6>点击量:{{ article.click_num }}</h6>
                <h6>收藏量:{{ article.save_num }}</h6>
                <h6>喜欢:{{ article.love_num }}</h6>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/user/myphoto.html
{% extends 'base.html' %}
{% block title %}
    相册列表
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
        }

        .photo img {
            width: 50%;
            height: 50%;
        }

        .photo {
            text-align: center;
            margin-top: 30px;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        {% for paginate in pagination.items %}

            <div class="photo">
                <img src="http://qmvgt21j4.hn-bkt.clouddn.com/{{ paginate.photo_name}}" alt="">

            </div>
        {% endfor %}
        <nav aria-label="...">
            <ul class="pager">
                <li class="previous {% if not pagination.has_prev %}disabled{% endif %}"><a href="{{ url_for('user.myphoto', page=pagination.prev_num) }}"><span aria-hidden="true">&larr;</span> 上一页</a></li>
                <li class="next {% if not pagination.has_next %}disabled{% endif %}"><a href="{{ url_for('user.myphoto', page=pagination.next_num) }}">下一页 <span aria-hidden="true">&rarr;</span></a></li>
            </ul>
        </nav>
    </div>
{% endblock %}